Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%%bash
# Read the first 100 characters from the file
head -c 100 foo.hdf5

with open("module10_scientific_file_formats/foo.hdf5", "rb") as f_in:bytes = f_in.read()
...
>>> bytes[0:100]
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mCalledProcessError[0m                        Traceback (most recent call last)
Cell [0;32mIn [21], line 1[0m
[0;32m----> 1[0m [43mget_ipython[49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43mrun_cell_magic[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mbash[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43m# Read the first 100 characters from the file[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43mhead -c 100 foo.hdf5[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;130;43;01m\n[39;49;00m[38;5;124;43mwith open([39;49m[38;5;124;43m"[39;49m[38;5;124;43mmodule10_scientific_file_formats/foo.hdf5[39;49m[38;5;124;43m"[39;49m[38;5;124;43m, [39;49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[38;5;124;43m) as f_in:bytes = f_in.read()[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43m...[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43m>>> bytes[0:100][39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/IPython/core/interactiveshell.py:2417[0m, in [0;36mInteractiveShell.run_cell_magic[0;34m(self, magic_name, line, cell)[0m
[1;32m   2415[0m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39mbuiltin_trap:
[1;32m   2416[0m     args [38;5;241m=[39m (magic_arg_s, cell)
[0;32m-> 2417[0m     result [38;5;241m=[39m [43mfn[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m   2418[0m [38;5;28;01mreturn[39;00m result

File [0;32m/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/IPython/core/magics/script.py:153[0m, in [0;36mScriptMagics._make_script_magic.<locals>.named_script_magic[0;34m(line, cell)[0m
[1;32m    151[0m [38;5;28;01melse[39;00m:
[1;32m    152[0m     line [38;5;241m=[39m script
[0;32m--> 153[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mshebang[49m[43m([49m[43mline[49m[43m,[49m[43m [49m[43mcell[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/IPython/core/magics/script.py:305[0m, in [0;36mScriptMagics.shebang[0;34m(self, line, cell)[0m
[1;32m    300[0m [38;5;28;01mif[39;00m args[38;5;241m.[39mraise_error [38;5;129;01mand[39;00m p[38;5;241m.[39mreturncode [38;5;241m!=[39m [38;5;241m0[39m:
[1;32m    301[0m     [38;5;66;03m# If we get here and p.returncode is still None, we must have[39;00m
[1;32m    302[0m     [38;5;66;03m# killed it but not yet seen its return code. We don't wait for it,[39;00m
[1;32m    303[0m     [38;5;66;03m# in case it's stuck in uninterruptible sleep. -9 = SIGKILL[39;00m
[1;32m    304[0m     rc [38;5;241m=[39m p[38;5;241m.[39mreturncode [38;5;129;01mor[39;00m [38;5;241m-[39m[38;5;241m9[39m
[0;32m--> 305[0m     [38;5;28;01mraise[39;00m CalledProcessError(rc, cell)

[0;31mCalledProcessError[0m: Command 'b'# Read the first 100 characters from the file\nhead -c 100 foo.hdf5\n\nwith open("module10_scientific_file_formats/foo.hdf5", "rb") as f_in:bytes = f_in.read()\n...\n>>> bytes[0:100]\n'' returned non-zero exit status 2.
CalledProcessError: Command 'b'# Read the first 100 characters from the file\nhead -c 100 foo.hdf5\n\nwith open("module10_scientific_file_formats/foo.hdf5", "rb") as f_in:bytes = f_in.read()\n...\n>>> bytes[0:100]\n'' returned non-zero exit status 2.

